### ISSUE TITLE
Allow nested objects to be used in logging context data

### ISSUE THREAD

**Issue by scopendo** [DataDog/dd-sdk-flutter#142]
**Is your feature request related to a problem? Please describe.**
It does not appear to be possible to log a data object if that object contains Dart enum values.  For example, I have a data object where the class has been generated by the popular `Freezed` package, which includes attributes that are enum values.  If I try to log such an object then I get an error:

> flutter: [Datadog 🐶⚠️ ] ArgumentError when calling logs.info: parameter null could not be properly converted to a supported native type.

Here is a simplified example.

```dart
enum PlaceName {
  organisation,
  reception,
}

@freezed
class HomeSettings with _$HomeSettings {
  const factory HomeSettings({
    @Default(PlaceName.organisation) PlaceName placeName,
  }) = _HomeSettings;

  const HomeSettings._();

  factory HomeSettings.fromJson(Map<String, dynamic> json) =>
      _$HomeSettingsFromJson(json);
}
```

```
final settings = HomeSettings(placeName: PlaceName.reception);

// This won't work as the settings object contains a enum value
DatadogSdk.instance.logs?.info(
  'example', 
  {
    'settings': settings.toJson(),
  },
);
```

**Describe the solution you'd like**
Add support for logging of values that can be encoded as JSON.

**Comment by fuzzybinary** [comment]
Hi @scopendo!

I tried to replicate your example and with freezed 2.0.3+1 and json_serializable 6.2.0 this works as expected so long as you do what's listed and convert the object to Json first, since json_serialziable converts those properly to strings.

<img width="252" alt="image" src="https://user-images.githubusercontent.com/249982/172415230-b57a3326-b5b7-496a-9411-182e77102712.png">

Generally, anything that is valid JSON will work when passed as an attribute to any call that needs accepts `context`.

Can you take another look at the Map resulting from your .toJson call and see if there's another possible cause other than the enum? A nested object maybe?

**Comment by fuzzybinary** [comment]
@scopendo Agreed, I will look into that as a separate issue.

**Comment by scopendo** [comment]
It looks like the issue isn't really to do with enums but more to do with nested (freezed) sub-objects.  I'm still to prepare an example, however, I've found a workaround to be encoding and decoding:

```dart
Datadog.instance.rum?.addTapAction('setup_done', {
  'settings': jsonDecode(jsonEncode(settings.toJson())),
});
```

**Comment by fuzzybinary** [comment]
I think this is just a weird behavior of json_serializable that it doesn't actually serialize nested objects by default. Here's a bit more detail:
https://docs.flutter.dev/development/data-and-backend/json#generating-code-for-nested-classes

It looks like if you add:
```dart
@JsonSerializable(explicitToJson: true)
```
above your class is will correctly navigate to children and serialize them to JSON with just the `.toJson()` call.

Let me know if that works and we can close this issue and I'll open a new one for properly logging these types of errors.

**Comment by fuzzybinary** [comment]
Closing in favor of #149
