### ISSUE TITLE
Failing to track RUM actions

### ISSUE THREAD

**Issue by yonjans** [DataDog/dd-sdk-flutter#382]
**Describe what happened**

I called `DdRum.instance.rum!.addUserAction` to send custom user actions but no actions are appearing in Datadog side. However, I can see my session, views, errors and default actions like `Application_start`. Its happening in Android but not sure about iOS.

**Steps to reproduce the issue:**

```
  final datadogConfiguration = DdSdkConfiguration(
    clientToken: currentPlatform() == Platform.android
        ? datadogConfig.androidClientToken
        : datadogConfig.iosClientToken,
    env: datadogConfig.flavorName,
    trackingConsent: TrackingConsent.granted,
    site: DatadogSite.eu1,
    serviceName: datadogConfig.serviceName,
    nativeCrashReportEnabled: true,
    rumConfiguration: RumConfiguration(
      applicationId: currentPlatform() == Platform.android
          ? datadogConfig.androidRumApplicationId
          : datadogConfig.iosRumApplicationId,
    ),
    loggingConfiguration: LoggingConfiguration(
      printLogsToConsole: true,
      sendNetworkInfo: true,
    ),
    uploadFrequency: UploadFrequency.frequent,
  );
  final datadogInstance = DatadogSdk.instance;
  await datadogInstance.initialize(datadogConfiguration);
  
  // on button tapped
  DatadogSdk.instance.rum!.addUserAction(actionType, name, attributes);
```
I do not see any error when `addUserAction` is called.

**Describe what you expected:**

Custom user actions being tracked in RUM Actions.

**Additional context**
 - Dart/Flutter version: `2.17.1`/`3.0.1`
 - Android/iOS OS version: 9
 - Device Model: HUAWEI nova 3e
 - Datadog SDK version: `1.1.0`
 - Versions of any other relevant dependencies:

**Comment by fuzzybinary** [comment]
Hi @yonjans ,

In order to track user actions you should make sure you start a view using `DatadogSdk.instance.rum?.startView`, or one of the methods of tracking view starts / stops automatically like `DatadogNavigationObserver` and / or `DatadogRouteAwareMixin`.

In version 1.3.0+, we do have a slight change in functionality that will always start a view on initial launch, called "ApplicationLaunch", that will remain active until your first call to `startView`, which should correctly capture this user interaction as well, but we still recommend starting a view instead of relying on the ApplicationLaunch view.

As an aside, I would also highly recommend you use optional chaining (?.) on the RUM dereference instead of the the force dereference (!.). This will make it easier for you if you decide to have builds that don't initialize RUM, since we don't provide a value for RUM if you don't initialize it.

Let me know if that fixes your issue!

**Comment by yonjans** [comment]
Thanks @fuzzybinary

But we are already using `DatadogNavigationObserver` and as said above we can also see views being updated. I forgot to add code in above issue description.

We used force dereference to throw error if it is not initialized so that we will know our issue is somewhere else. But even it has been initialized and platform method is getting invoked, we still can not see RUM action.

We are out of options to try here.

**Comment by fuzzybinary** [comment]
@yonjans 

Can you add `DatadogSdk.instance.sdkVerbosity = Verbosity.verbose` and see if the SDK is reporting any errors or warnings when attempting to add the action?

If that doesn't reveal anything actionable, can you reach out to Datadog support directly? That will allow me to take a look at the data that's being sent and maybe be able to diagnose what's going wrong.

**Comment by yonjans** [comment]
Thanks @fuzzybinary.

Adding `DatadogSdk.instance.sdkVerbosity = Verbosity.verbose` helped to debug the issue.

We were calling it from bottom sheet and somehow no view was active from the point we were sending the RUM actions.
