### ISSUE TITLE
[WEB] plugin is blocked if use some ad blockers

### ISSUE THREAD

**Issue by AlehSabadashGmail** [DataDog/dd-sdk-flutter#413]
**Describe what happened**
there is white screen after running app. Data dog logger wrap the whole app so when initialisation is failed running is also failing, in my case I just see white screen, no errors only this in console 
 App works correctly with some ad blokers(e.x. AdblockPlus)
 
 <img width="554" alt="Screenshot 2023-05-04 at 11 32 57" src="https://user-images.githubusercontent.com/90776958/236167092-e80d9f5e-d15c-4df0-9488-20a51e1422e9.png">
<img width="744" alt="Screenshot 2023-05-04 at 11 34 32" src="https://user-images.githubusercontent.com/90776958/236167455-577da4bf-a484-4900-8555-617d57d72f8b.png">

**Note! I guess it happens due to `tracking` part in the url**

**Steps to reproduce the issue:**
run app on the WEB -> turn on ad blocker (I use **uBlock Origin**) -> refresh page

**Describe what you expected:**
Should work if someone turn on any ad blockers

**Additional context**
 - Dart/Flutter version: 3.7.9
 - Datadog SDK version: 1.2.1

**Comment by fuzzybinary** [comment]
Hi @AlehSabadashGmail ,

This isn't technically a bug in the SDK, but I'll see if I can look into it.  It doesn't appear uBlock Origin blocks 'tracking' by default though...

The good part is that tracking_http_client isn't necessary for web, since the Browser SDK does all the work.  If you enclose the call to `enableHttpTracking` in `if (kIsWeb)`, tree shaking should remove the package import for you in release builds:

```dart
final configuration = DdSdkConfiguration(
  // your config
);
if (!kIsWeb) {
  configuration.enableHttpTracking();
}
```

Then I would just set an exception for localhost on your ad blocker.

Additionally, it's possible this is not an issue with packaged builds at all, as I believe the modules are compiled into one file instead of multiple.

Let me know if any of that works for you.

**Comment by AlehSabadashGmail** [comment]
Hey @fuzzybinary 
yeah, it works, thank you very much for your quick response, appreciate it
