### ISSUE TITLE
Zone mismatch after updating flutter v3.10.0

### ISSUE THREAD

**Issue by luisfelipeas5** [DataDog/dd-sdk-flutter#416]
**Describe what happened**
Running the app after update flutter to v3.10.0, the `Zone mismatch` exception started to be thrown calling `DatadogSdk.runApp`.

**Steps to reproduce the issue:**
- Run `flutter upgrade`;
- Run the app;
- See the exception been thrown on Debug Console.

Here my code:
```dart
Future<void> startApp() async {
    WidgetsFlutterBinding.ensureInitialized();

    if (kDebugMode) {
      HttpOverrides.global = CustomHttpOverrides();
    }

    await Firebase.initializeApp();

    SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);

    await DatadogSdk.runApp(
      _dataDogConfiguration,
      () async {
        runApp(
          ModularApp(
            module: AppModule(buildConfig),
            child: const AppWidget(),
          ),
        );
      },
    );
  }

  DdSdkConfiguration get _dataDogConfiguration {
    return DdSdkConfiguration(
      clientToken: buildConfig.dataDogClientToken,
      env: buildConfig.environmentName,
      site: DatadogSite.us1,
      trackingConsent: TrackingConsent.granted,
      nativeCrashReportEnabled: true,
      loggingConfiguration: LoggingConfiguration(
        sendLogsToDatadog: !kDebugMode,
      ),
      rumConfiguration: RumConfiguration(
        applicationId: '...',
      ),
    );
  }
```

**Describe what you expected:**
Same behavior when I run the app with flutter v3.7.12: no erros when `DatadogSdk.runApp`

**Additional context**
 - Dart/Flutter version: 3.10.0
 - Android/iOS OS version: Android 13 / iOS 16.4
 - Device Model: Android emulator Pixel 5 / iPhone 14 Pro
 - Datadog SDK version: 1.4.0

**Comment by fuzzybinary** [comment]
Hi @luisfelipeas5,

I'll look into this soon, but to get you back up and running quickly, you can replace `DatadogSdk.runApp` with the following function:

```dart
Future<void> newRunApp(
    DdSdkConfiguration configuration, AppRunner runner) async {
  final originalOnError = FlutterError.onError;
  FlutterError.onError = (details) {
    DatadogSdk.instance.rum?.handleFlutterError(details);
    originalOnError?.call(details);
  };
  PlatformDispatcher.instance.onError = (error, stack) {
    DatadogSdk.instance.rum?.addErrorInfo(
      error.toString(),
      RumErrorSource.source,
      stackTrace: stack,
    );
    return false;
  };
  await DatadogSdk.instance.initialize(configuration);
  runner();
}
```

We've wanted to move from `runZonedGuarded` to Flutter's recommended `PlatformDispatcher.instance.onError` for some time, but needed to keep `runZonedGuarded` for backwards compatibility reasons. 1.4.x may finally perform this replacement.

**Comment by luisfelipeas5** [comment]
Great! Thank you. It's working ✨ 
Waiting for the new versions then.

Is it better close the issue now or just when the version was released?

**Comment by fuzzybinary** [comment]
Leave it open and I'll use it to track switching from `runZonedGuarded` to `PlatformDispatcher.instance.onError`

**Comment by fuzzybinary** [comment]
By the way for anyone else looking at this -- the zone mismatch is partially due to the use of `WidgetsFlutterBinding.ensureInitialized()` outside of `DatadogSdk.runApp`. We run that internally in `runApp` inside the zone. Running it outside the zone means that it's possible some errors are being missed.  

This has always been the case, it's just Flutter 3.10 added an exception for it apparently.

So folks reading you have a few solutions. 
1. The best is to use the above example that uses `PlatformDispatcher.instance.onError` instead of `runZonedGuarded`.
2. Wrap your entire run method (including any calls to `WidgetsFlutterBinding.ensureInitialized()` with `runZonedGuarded` and report errors to Datadog manually following [this documentation](https://docs.datadoghq.com/real_user_monitoring/flutter/setup/#initialize-the-library)
3. Move all initialization code into `Datadog.runApp` and remove calls to `WidgetsFlutterBinding.ensureInitialized`
4. Wait for us to update to using `PlatformDispatcher.instance.onError`, which should be coming either in 1.4.1 or 1.5 hopefully sometime next week.
