### ISSUE TITLE
Should be possible to use Dio interceptor to track request

### ISSUE THREAD

**Issue by Kiruel** [DataDog/dd-sdk-flutter#451]
**Is your feature request related to a problem? Please describe.**
I would like to use Dio client to trace my request to datadog.

**Describe the solution you'd like**
I saw in the unofficial library this interceptor https://github.com/GetDutchie/datadog_flutter/issues/47#issuecomment-915049269 that can be fit my need.

**Describe alternatives you've considered**
I was trying using `startResourceLoading` and `stopResourceLoading` but with no result, the data is not send to datadog. And if I use `enableHttpTracking` he do not track the query title etc...

**Additional context**
I'm using Dio with graphql to perform some query etc... this is the code I use to configure the graphql:
```dart
@Riverpod(keepAlive: true)
GraphQLClient graphQlClient(GraphQlClientRef ref) => GraphQLClient(
      cache: GraphQLCache(
        store: kIsWeb
            ? InMemoryStore()
            : HiveStore(
                Hive.box<Map<dynamic, dynamic>?>(hiveBoxVersion),
              ),
      ),
      defaultPolicies: DefaultPolicies(
        mutate: Policies(fetch: FetchPolicy.networkOnly),
        query: Policies(fetch: FetchPolicy.networkOnly),
        subscribe: Policies(fetch: FetchPolicy.networkOnly),
        watchMutation: Policies(fetch: FetchPolicy.networkOnly),
        watchQuery: Policies(fetch: FetchPolicy.networkOnly),
      ),
      link: Link.from([
        ErrorLink(
          onGraphQLError: (request, forward, response) {
            if (response.errors?.first.extensions?['code'] == 'UNAUTHORIZED') {
              // Here capture errors from graphql
            }
            return;
          },
        ),
        DioLink(
          'GRAPHQL_API_URL',
          client: Dio(
            BaseOptions(
              baseUrl: 'BASE_URL',
              connectTimeout: const Duration(milliseconds: 5000),
              receiveTimeout: const Duration(milliseconds: 20000),
              contentType: Headers.jsonContentType,
            ),
          )
            ..interceptors.add(
              // here I would like to add interceptor to track my graphql query/mutation ...
            )
        ),
      ]),
    );
```

**Comment by Kiruel** [comment]
Hi @fuzzybinary , thanks for quick reply. 

Yes I saw the session in RUM. And if I activate the `enableHttpTracking` I can see some event in the APM trace but in the column ressource I saw only the baseUrl of my graphql `https://my_domain/api/graphql` for example. 

That why I try to create an interceptor to manually send the ressource key with the correct name from the graphql but with no result.

In comparaison on the server side (nodejs typescript with the service service activated) I saw the query in the ressource column.

**Comment by fuzzybinary** [comment]
This may be related to #397, I give a few solutions in that issue. We're working on better ways to integrate GraphQL specifically, but unfortunately it's not ready yet.

You should be able to use `startResouceLoading` and `stopResourceLoading`, but you won't get distributed traces in APM without doing a bit of extra work (you need to add some headers to your request as well as attributes to the resource in order to get them to connect).

For my knowledge what GraphQL library are you using, and does it support the `gql_link` package?

**Comment by Kiruel** [comment]
By extra work what do you mean exactly ? Where I can find documentation about `startResouceLoading` etc... and how to link trace from frontend to backend ? I will try to make an interceptor on my Dio.

For the GraphQL library I'm using [`graphql_flutter` ](https://pub.dev/packages/graphql_flutter) and yes it support `gql_link` using this library: [`gql_dio_link`](https://pub.dev/packages/gql_dio_link). You can find in the code `DioLink`.

More information on how graphql links works [here]( https://github.com/zino-hofmann/graphql-flutter/blob/main/packages/graphql/README.md#links).
>graphql and graphql_flutter now use the [gql_link](https://github.com/gql-dart/gql/tree/master/links/gql_link) system, re-exporting [gql_http_link](https://pub.dev/packages/gql_http_link), [gql_error_link](https://pub.dev/packages/gql_error_link), [gql_dedupe_link](https://pub.dev/packages/gql_dedupe_link), and the api from [gql_link](https://pub.dev/packages/gql_link), as well as our own custom WebSocketLink and AuthLink.
This makes all link development coordinated across the ecosystem, so that we can leverage existing links like [gql_dio_link](https://pub.dev/packages/gql_dio_link), and all link-based clients benefit from new link development (such as [ferry](https://github.com/gql-dart/ferry)).

**Comment by fuzzybinary** [comment]
Documentation on startResourceLoading / stopResourceLoading can be found in the API reference on pub.dev - https://pub.dev/documentation/datadog_flutter_plugin/latest/datadog_flutter_plugin/DdRum-class.html

I don't think we have full documentation on RUM to APM but you can look at the code for the `http` package here: https://github.com/DataDog/dd-sdk-flutter/blob/8511cc5e3802921a8ef9078c4220fdd4c8ba2051/packages/datadog_tracking_http_client/lib/src/tracking_http.dart#L217

Note that we support several trace types but the only you probably want is the Datadog type.

Last thing to mention because I forgot to ask, can you double check your sampling rate? By default, the tracing sampling rate is 20%, not 100%. This won't affect if you set up tracing headers manually, but does affect automatic tracing. https://pub.dev/documentation/datadog_flutter_plugin/latest/datadog_flutter_plugin/RumConfiguration/tracingSamplingRate.html

**Comment by fuzzybinary** [comment]
[`datadog_gql_link`](https://pub.dev/packages/datadog_gql_link) is now live as an official package. I think that's the main request of this ticket so I'm going to close it for now. Let me know if you have any issues with the new package!

**Comment by Kiruel** [comment]
Wow nice work ! Thank !
