### ISSUE TITLE
the two parameters "proxy" and "customEndpoint" are equivalent, but why the different names?

### ISSUE THREAD

**Issue by magiepooh** [DataDog/dd-sdk-flutter#625]
### Question

I think the two parameters "proxy" and "customEndpoint" are equivalent, but why the different names?
https://docs.datadoghq.com/ja/real_user_monitoring/guide/proxy-rum-data/?tab=npm

In FlutterSDK you just pass the value.
https://github.com/DataDog/dd-sdk-flutter/blob/a5657fe3aa7a944b2849de9f93be4936d5689833/packages/datadog_flutter_plugin/lib/src/logs/ddlogs_web.dart#L24

Is it possible to unify these names?

**Comment by fuzzybinary** [comment]
Hi @magiepooh,

For un-authenticated proxies, they will act the same. For proxies that require authentication or additional options, the `customEndpoint` won't be configurable enough, and it's mostly used internally for testing and debugging.

The iOS and Android SDKs offer separate properties for Proxy configuration which are, unfortunately, not currently exposed to the Flutter SDK (see [this on iOS](https://github.com/DataDog/dd-sdk-ios/blob/380bdf4938519b676d5a1d06bd2ce6928637a0a6/DatadogCore/Sources/Datadog.swift#L109) and  [this on Android](https://github.com/DataDog/dd-sdk-android/blob/1ee400d4217de3d4fdf4eff226f25241a0f0ced8/dd-sdk-android-core/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt#L207))

If you have need of these methods because `customEndpoint` is insufficiently configurable, please open another issue as a feature request.

Thanks!
