### ISSUE TITLE
Traces are not working

### ISSUE THREAD

**Issue by acoutts** [DataDog/dd-sdk-flutter#84]
I am trying to add tracing manually, following the approach used in `DatadogTrackingHttpOverrides`.

I start a trace:
```dart
final tracingSpan = tracer.startSpan(
          'grpc.client',
          resourceName: method.path,
          tags: {
            'grpc.path': method.path,
          },
        );
```

After the GRPC call finished I finish the span:
```dart
tracingSpan.finish();
```

But I don't see any of the events showing up in the UI:
<img width="1016" alt="Screen Shot 2022-04-07 at 1 48 33 PM" src="https://user-images.githubusercontent.com/9597207/162265335-f2511267-dc20-4980-9d1e-9344df208703.png">

I'm using version `1.0.0-alpha.1`

**Comment by xgouchet** [comment]
Hi @acoutts, 

The screenshot you're showing is on the RUM Session, which represent a whole user journey in your application. To see smaller events, you need to look at the View (in your case the `HomeScopeRoute…` view). In there you should be able to see network requests tracked as RUM Resource, and your trace should be visible in the `Traces` tab of the View. 

Secondly, since you're using RUM you might want to also track your gRPC request as a Resource, using the `rum.startResourceLoading(resourceKey, httpMethod, url, attributes)` and `rum.stopResourceLoading(resourceKey, statusCode, resourceType, size)` methods (you can see how we generate each parameters in our [DatadogTrackingHttpClient](https://github.com/DataDog/dd-sdk-flutter/blob/develop/packages/datadog_tracking_http_client/lib/src/tracking_http_client.dart)  implementation

**Comment by acoutts** [comment]
Thanks, I was able to find the traces in the UI but am stuck on a limitation in `grpc-dart`- in order to implement the same kind of `DatadogTrackingHttpClient` for the GRPC client, i have to use their interceptor api but it's not async which means I can't call into the datadog sdk to get the trace headers (and add them to the GRPC request on its way out).

https://github.com/grpc/grpc-dart/issues/544

**Comment by fuzzybinary** [comment]
Hey @acoutts,

We are considering moving away from using platform spans for RUM resource tracking for partially this reason, and will generate the trace and span ids on the Dart side instead (at least for RUM).

As a workaround, you can actually generate your own traceId and spanId without creating a platform span, add them in the proper attributes (`DatadogPlatformAttributeKey.traceID` and `DatadogPlatformAttributeKey.spanID`) and it will work correctly.

Trace and SpanIds are just 36-bit values, and I think Dart's `Random().nextInt(68719476736)`  should give you enough variance to work fine (@xgouchet will correct me if I'm wrong about this).

**Comment by fuzzybinary** [comment]
@acoutts I've been experimenting with creating a gRPC interceptor using the above approach.

It's not ready for release on pub, but if you'd like to give it a try you can add it as a git dependency. I'd love to hear if it works for you.

```yaml
dependencies:
  datadog_grpc_interceptor:
    git:
      url: git@github.com:DataDog/dd-sdk-flutter.git
      path: packages/datadog_grpc_interceptor
      ref: develop
```

**Comment by fuzzybinary** [comment]
Closing this since we haven't gotten a response. If you're still having an issue or have feedback on the grpc library, please re-open.

**Comment by acoutts** [comment]
Doing some more looking into this one - i tried your code but it never sends any trace because in my case my host doesn't have https:// on it but it's still a valid grpc channel.

I made a fork to handle both cases when the grpc channel contains a scheme or not and it's working for my setup now: https://github.com/DataDog/dd-sdk-flutter/pull/167

**Comment by fuzzybinary** [comment]
Thanks @acoutts. Going to re-open while we hammer out final steps with your PR, then we'll close when it's actually fixed.
